# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25339d863bd28d7881b486a0bbdb9b882b5e1f380c9f159b98c2d5dd8152657fc54741ffa187987de1ea290e44e02e17755453cd66a884d2248dc67381d39d5b

test:
  secret_key_base: b888f317f1deb8013b1909d6d895bda05850aa622511bbf885a851f7cd5255e9c12baf84cab7631a3f9d35d1bfd9a0ea58915fe570e7bb20fde6c4f467bce5bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
